name: License Checker

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: License Checker
        uses: kt3k/license_checker@v1.0.1
